# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: deb067f68b1f5e68aee2d086f092b556f52d710cb9d998818948de25c06f6773db003161cc89d75cd278f9f51dc12d21e836fba5685ae51772a77fead857fee6

test:
  secret_key_base: 9e37e44cda07ca0a3957ce0d37b6418a149095e1a821a9789a2c93ed6f16204f36fb65cb4610994f6d2a6261e0b7143b64c338adb387bd63d0357f45d9a4d7d8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
